### ISSUE TITLE
I want to understand you common module step by step

### ISSUE THREAD

**Issue by manojsharma20** [eugenp/REST-With-Spring#75]
Hi,

I want to understand you common module step by step which you are using almost every tutorial. Is there any source or tutorial which let me understand your common module.

**Comment by eugenp** [comment]
Hey @manojsharma20 - the common module simply holds a few utilities that are not business specific, they're just common infrastructure. 
I don't think there's any dedicated writeup for it. 
Let me know if there's any class/component in particular there that you're curious about. 

Cheers, 
Eugen.

**Comment by manojsharma20** [comment]
I liked the way you write the dao. I am curious about only the Dao part which you have implemented with service and service impl.

I want to understand the whole part. I am able to understand your common interfaces, but the rest part from service to dao, service impl, I am not able to understand.

If you can make it clear for me it will be good to implement.

I am very fan of your code you have written in common module.

**Comment by eugenp** [comment]
I'm glad you're enjoying the code @manojsharma20 - so, about the REST aspects - it's basically a layered design, where you have: the DB -> the DAO/Repository layer -> Service layer -> Controller/Web layer
So that's what you need to keep in mind as you read through the code - you'll see that each layer injects the one below it. 

Hope that starts clearing things up. Of course you'll need to explore the codebase more to fully understand everything. 
The good thing is that this is a simple example, so the domain is quite small. 

Cheers, 
Eugen.

**Comment by manojsharma20** [comment]
Is there any source where i can understand step by step like which interface or class create first and so on.

**Comment by eugenp** [comment]
Sure @manojsharma20  - have a look at the lesson notes (and the end - I added a new section). 
Cheers, 
Eugen.
